root: true

env:
    node: true

extends: "eslint"

rules:
    no-underscore-dangle: [2, { "allow": ["_id"] }]
    space-before-function-paren: [2, {"anonymous": "always", "named": "never"}]

globals:
    "jQuery": false,
    "_": false,
    "depot": false
